Create pipeline to transfer data from Snowflake to local PostgreSQL D…
producepay/ETL-Kyle-Test pull request #1
Opened 2024-08-09 23:54 UTC by KyleHong7

…B. Retrieve tables from the 'mp_visibility' schema in Snowflake. Load data into PostgreSQL with correct formatting.

2024-08-12 19:55 UTC, jmamato requested changes
Over-all good code. 

Once you update the environmental file handling to automaticaly exclude from any git commit and push we can approve and move to the next steps.

I'll follow up with you in Slack regarding how to modify this to accommodate rerunning as a daily or more frequent process.

2024-08-12 19:55 UTC, jmamato commented on visibility_el.py
> +import json
a second import will return the previous import reference. Were you expecting a certain behavior importing json two times? I suspect it's just a copy paste typo. Just want to make sure.

2024-08-12 19:55 UTC, jmamato commented on visibility_el.py
> +        env = get_env("/Users/testuser/Documents/Projects/producepay/ELT_test/visibility_env.json")
the .env file name provided in the code snipet is a python standard. A file that starts with a . automatically is ignored by most git repo configs. It is also hidden in most operating systems. Barring following that better practice please add this filename to a .gitignore file in the root directory of the repo. Otherwise you would need to keep remembering that you don't want to add it to your repo. This is a security issue so we need to be extra mindful we don't accidently push non-secure credential files into the repo.

2024-08-12 21:24 UTC, KyleHong7 commented on visibility_el.py
> +    import json
I thought it was good practice to have both. Since Simplejson is more efficient from what I know, and having a fallback would've been helpful in case Simplejson didn't work as expected. 

If it's not a frequent event, then I will remove it. Probably brings more confusion then necessary.

2024-08-12 21:27 UTC, KyleHong7 commented on visibility_el.py
> +import json
Oops, I forgot to remove the original Json import after revising it into simplejson. Just a typo mistake.

2024-08-12 21:31 UTC, KyleHong7 commented on visibility_el.py
> +        env = get_env("/Users/testuser/Documents/Projects/producepay/ELT_test/visibility_env.json")
That's good to know, I'll make those adjustments to my code and resubmit it. Thanks!

2024-08-12 22:04 UTC, jmamato commented on visibility_el.py
> +    import json
In order to have both you'd need both libraries installed and not imported as the same json alias. 

The try only allows one or the other to load. This would be used in the case that you have multiple python environments this would need to run your python. One has simplejson and the other only json. This allows the same script to work on both. It would be a limited solution as more often when a solution has multiple libraries they do not implement the same functions, procedures, and parameters.

2024-08-12 22:55 UTC, KyleHong7 commented on visibility_el.py
> +    import json
I understand the underlying logic, and initially I was leaning towards the latter approach. I noticed Python comes with an in-built JSON library; however, I recognized that SimpleJSON was often utilized for its efficiency. Therefore, creating a fallback in case SimpleJSON isn't available in order to leverage the faster SimpleJSON. 

But I now recognize how it can create conflicts, as you highlighted, which will result in different functions, procedures, and parameters. I appreciate the feedback. 

2024-08-13 18:23 UTC, jmamato approved these changes
looks good for this iteration.

2024-08-13 18:42 UTC, merged